id: e994334b-dc60-4b95-88c0-327f71d55daf
name: CustomerCare
type: application
description: Application layer
author: CodeArchitects
namespace: Ca.CaepFlow
modelNamespace: Ca.CaepFlow.Model
rootNamespace: Ca.CaepFlow.Containers
baseApiUrl: ca/caepflow
isFederable: true
interactions:
  - type: domain
    targetId: ad520394-2616-4059-91ad-20ba13be21a3
    level: component
annotations:
  - namespace: c4modeler
    name: position
    value:
      component:
        x: 408.9040485404535
        y: 73.97138996386248
